/* Brandon Hall beverage stock — from stock take 21 Sept 2026 (117 products).
   price = latest ex-VAT case/order-unit price. stock = physical count (order units).
   perCase = selling units per case (for single-bottle removal). */
const BEV_PRODUCTS = [
  {"id": "bev-001", "cat": "Beer & Lager", "sup": "Matthew Clark", "code": "00026639", "name": "Corona 4.5%", "pack": "330ml x24", "unit": "Case", "perCase": 24, "price": 25.09, "stock": 6.5},
  {"id": "bev-002", "cat": "Beer & Lager", "sup": "Brakes", "code": "119918", "name": "Peroni Nastro Gluten Free NRB", "pack": "330ml x24 (6x4)", "unit": "Case", "perCase": 24, "price": 37.45, "stock": 0.88},
  {"id": "bev-003", "cat": "Beer & Lager", "sup": "", "code": "", "name": "Kopperberg Strawberry & lime 0%", "pack": "12", "unit": "case", "perCase": 1, "price": 12.34, "stock": 1.83},
  {"id": "bev-004", "cat": "Beer & Lager", "sup": "Heineken", "code": "HK-HEIN00-NRB", "name": "Heineken 0.0 NRB (alcohol-free)", "pack": "330ml x24", "unit": "Case", "perCase": 24, "price": 42.04, "stock": 2.58},
  {"id": "bev-005", "cat": "Cider", "sup": "Matthew Clark", "code": "00033298", "name": "Bulmers Red Berry/Lime", "pack": "500ml x12", "unit": "Case", "perCase": 12, "price": 22.85, "stock": 2.83},
  {"id": "bev-006", "cat": "Kegs/Draught", "sup": "Heineken", "code": "HK-BEAV50", "name": "Beavertown Neck Oil IPA Keg 50L", "pack": "50L keg", "unit": "Keg", "perCase": 1, "price": 268.43, "stock": 3.1},
  {"id": "bev-007", "cat": "Kegs/Draught", "sup": "Heineken", "code": "HK-CRUZ50", "name": "Cruzcampo Keg 50L", "pack": "50L keg", "unit": "Keg", "perCase": 1, "price": 133.42, "stock": 2.9},
  {"id": "bev-008", "cat": "Kegs/Draught", "sup": "Heineken", "code": "HK-GUINNESS50", "name": "Guinness Original Keg 50L", "pack": "50L keg", "unit": "Keg", "perCase": 1, "price": 155.82, "stock": 1.7},
  {"id": "bev-009", "cat": "Kegs/Draught", "sup": "Heineken", "code": "HK-HEIN00-20", "name": "Heineken 0.0 Keg 20L", "pack": "20L keg", "unit": "Keg", "perCase": 1, "price": 0.0, "stock": 0.0},
  {"id": "bev-010", "cat": "Kegs/Draught", "sup": "Heineken", "code": "HK-MORETTI50", "name": "Birra Moretti Keg 50L", "pack": "50L keg", "unit": "Keg", "perCase": 1, "price": 150.26, "stock": 3.8},
  {"id": "bev-011", "cat": "Kegs/Draught", "sup": "Heineken", "code": "HK-ORCHARD30", "name": "Orchard Thieves Apples Keg 30L", "pack": "30L keg", "unit": "Keg", "perCase": 1, "price": 83.23, "stock": 2.4},
  {"id": "bev-012", "cat": "Liqueurs", "sup": "Matthew Clark", "code": "00010137", "name": "Drambuie", "pack": "70cl x6", "unit": "Each", "perCase": 6, "price": 21.46, "stock": 0.8},
  {"id": "bev-013", "cat": "Liqueurs", "sup": "Matthew Clark", "code": "00010637", "name": "Cointreau", "pack": "70cl x6", "unit": "Each", "perCase": 6, "price": 20.77, "stock": 1.8},
  {"id": "bev-014", "cat": "Liqueurs", "sup": "Matthew Clark", "code": "00015527", "name": "Disaronno Amaretto", "pack": "70cl x6", "unit": "Each", "perCase": 6, "price": 17.5, "stock": 0.8},
  {"id": "bev-015", "cat": "Liqueurs", "sup": "Matthew Clark", "code": "00015530", "name": "Baileys Irish Cream", "pack": "70cl x6", "unit": "Each", "perCase": 6, "price": 13.13, "stock": 3.6},
  {"id": "bev-016", "cat": "Liqueurs", "sup": "Matthew Clark", "code": "00020110", "name": "Aperol Aperitivo", "pack": "70cl x6", "unit": "Each", "perCase": 6, "price": 11.98, "stock": 3.7},
  {"id": "bev-017", "cat": "Liqueurs", "sup": "Matthew Clark", "code": "00022497", "name": "St Germain Elderflower Liqueur", "pack": "70cl x6", "unit": "Each", "perCase": 6, "price": 28.17, "stock": 0.9},
  {"id": "bev-018", "cat": "Liqueurs", "sup": "Matthew Clark", "code": "00029384", "name": "Briot Creme de Cacao Dark", "pack": "70cl x6", "unit": "Each", "perCase": 6, "price": 23.03, "stock": 1.8},
  {"id": "bev-019", "cat": "Liqueurs", "sup": "Matthew Clark", "code": "00031499", "name": "Edinburgh R & G Liqueur 20%", "pack": "50cl x6", "unit": "Each", "perCase": 6, "price": 10.52, "stock": 1.0},
  {"id": "bev-020", "cat": "Liqueurs", "sup": "Matthew Clark", "code": "00040723", "name": "Kahlua Coffee Liqueur", "pack": "70cl x6", "unit": "Each", "perCase": 6, "price": 14.52, "stock": 1.5},
  {"id": "bev-021", "cat": "Liqueurs", "sup": "Matthew Clark", "code": "00045236", "name": "Malibu", "pack": "1.5L x6", "unit": "Each", "perCase": 6, "price": 27.01, "stock": 1.3},
  {"id": "bev-022", "cat": "Liqueurs", "sup": "Matthew Clark", "code": "00046985", "name": "M Briz Cacao Brown 20% Liqueur", "pack": "70cl x6", "unit": "Each", "perCase": 6, "price": 9.8, "stock": 0.9},
  {"id": "bev-023", "cat": "Soft Drinks & Mixers", "sup": "Matthew Clark", "code": "00040437", "name": "Britvic Lime Cordial PET", "pack": "1L x12", "unit": "Case", "perCase": 12, "price": 24.67, "stock": 0.47},
  {"id": "bev-024", "cat": "Soft Drinks & Mixers", "sup": "Matthew Clark", "code": "00040439", "name": "Britvic Blackcurrant Cordial PET", "pack": "1L x12", "unit": "Case", "perCase": 12, "price": 24.67, "stock": 1.41},
  {"id": "bev-025", "cat": "Soft Drinks & Mixers", "sup": "Matthew Clark", "code": "00042132", "name": "Harrogate Still NRB", "pack": "330ml x24", "unit": "Case", "perCase": 24, "price": 8.77, "stock": 10.17},
  {"id": "bev-026", "cat": "Soft Drinks & Mixers", "sup": "Matthew Clark", "code": "00042133", "name": "Harrogate Sparkling NRB", "pack": "750ml x12", "unit": "Case", "perCase": 12, "price": 8.21, "stock": 2.92},
  {"id": "bev-027", "cat": "Soft Drinks & Mixers", "sup": "Matthew Clark", "code": "00042134", "name": "Harrogate Sparkling NRB", "pack": "330ml x24", "unit": "Case", "perCase": 24, "price": 8.77, "stock": 1.46},
  {"id": "bev-028", "cat": "Soft Drinks & Mixers", "sup": "Brakes", "code": "10734", "name": "Folkingtons Pure Orange Juice", "pack": "250ml", "unit": "Each", "perCase": 1, "price": 13.49, "stock": 83.0},
  {"id": "bev-029", "cat": "Soft Drinks & Mixers", "sup": "Brakes", "code": "10735", "name": "Folkingtons Pure Apple Juice", "pack": "250ml", "unit": "Each", "perCase": 1, "price": 14.49, "stock": 58.0},
  {"id": "bev-030", "cat": "Soft Drinks & Mixers", "sup": "Brakes", "code": "FT-TONIC", "name": "Fever Tree Tonic Water", "pack": "200ml x8 (pack faded)", "unit": "Case", "perCase": 8, "price": 17.44, "stock": 15.12},
  {"id": "bev-031", "cat": "Soft Drinks & Mixers", "sup": "Heineken", "code": "HK-COKE-NRB", "name": "Coca Cola NRB", "pack": "330ml x24", "unit": "Case", "perCase": 24, "price": 32.23, "stock": 4.38},
  {"id": "bev-032", "cat": "Soft Drinks & Mixers", "sup": "Heineken", "code": "HK-COKEZERO-NRB", "name": "Coca Cola Zero NRB", "pack": "330ml x24", "unit": "Case", "perCase": 24, "price": 30.09, "stock": 4.96},
  {"id": "bev-033", "cat": "Soft Drinks & Mixers", "sup": "Heineken", "code": "HK-DIETCOKE-NRB", "name": "Diet Coke NRB", "pack": "330ml x24", "unit": "Case", "perCase": 24, "price": 30.18, "stock": 5.12},
  {"id": "bev-034", "cat": "Soft Drinks & Mixers", "sup": "Heineken", "code": "HK-FRANKLIN", "name": "Franklin Brewed Ginger Beer", "pack": "200ml x24", "unit": "Case", "perCase": 24, "price": 20.45, "stock": 1.25},
  {"id": "bev-035", "cat": "Soft Drinks & Mixers", "sup": "Heineken", "code": "HK-FT-LIGHTTON", "name": "Fever Tree Light Tonic Water", "pack": "200ml x24", "unit": "Case", "perCase": 24, "price": 16.94, "stock": 5.38},
  {"id": "bev-036", "cat": "Soft Drinks & Mixers", "sup": "Heineken", "code": "HK-FT-PREMLEM", "name": "Fever Tree Premium Lemonade NRB", "pack": "200ml x24", "unit": "Case", "perCase": 24, "price": 17.93, "stock": 1.21},
  {"id": "bev-037", "cat": "Soft Drinks & Mixers", "sup": "Heineken", "code": "HK-FT-SODA", "name": "Fever Tree Soda Water NRB", "pack": "200ml x24", "unit": "Case", "perCase": 24, "price": 16.94, "stock": 2.42},
  {"id": "bev-038", "cat": "Soft Drinks & Mixers", "sup": "Heineken", "code": "HK-J2O-APPMAN", "name": "J2O Apple & Mango NRB", "pack": "275ml x24", "unit": "Case", "perCase": 24, "price": 27.9, "stock": 2.08},
  {"id": "bev-039", "cat": "Soft Drinks & Mixers", "sup": "Heineken", "code": "HK-J2O-APPRASP", "name": "J2O Apple & Raspberry NRB", "pack": "275ml x24", "unit": "Case", "perCase": 24, "price": 27.9, "stock": 2.04},
  {"id": "bev-040", "cat": "Soft Drinks & Mixers", "sup": "Heineken", "code": "HK-J2O-ORGPAS", "name": "J2O Orange & Passionfruit NRB", "pack": "275ml x24", "unit": "Case", "perCase": 24, "price": 27.9, "stock": 2.75},
  {"id": "bev-041", "cat": "Sparkling", "sup": "Matthew Clark", "code": "00029604", "name": "Galanti Prosecco Frizzante", "pack": "75cl x6", "unit": "Each", "perCase": 6, "price": 7.43, "stock": 10.9},
  {"id": "bev-042", "cat": "Sparkling", "sup": "", "code": "", "name": "Galanti Prosecco Rose", "pack": "", "unit": "Each", "perCase": 1, "price": 7.43, "stock": 6.0},
  {"id": "bev-043", "cat": "Sparkling", "sup": "Matthew Clark", "code": "00044719", "name": "Casa Bottega Prosecco", "pack": "75cl x6", "unit": "Each", "perCase": 6, "price": 7.78, "stock": 0.0},
  {"id": "bev-044", "cat": "Sparkling/Champagne", "sup": "Matthew Clark", "code": "00011087", "name": "Taittinger Brut Reserve", "pack": "75cl x6", "unit": "Each", "perCase": 6, "price": 33.45, "stock": 4.0},
  {"id": "bev-045", "cat": "Spirits - Cognac", "sup": "Heineken", "code": "HK-COURVOISIER", "name": "Courvoisier VS 40%", "pack": "70cl", "unit": "Each", "perCase": 1, "price": 24.57, "stock": 0.4},
  {"id": "bev-046", "cat": "Spirits - Gin", "sup": "Matthew Clark", "code": "00015492", "name": "Bombay Sapphire Gin", "pack": "70cl x6", "unit": "Each", "perCase": 6, "price": 19.68, "stock": 6.2},
  {"id": "bev-047", "cat": "Spirits - Gin", "sup": "Matthew Clark", "code": "00027837", "name": "Gin Mare", "pack": "70cl x6", "unit": "Each", "perCase": 6, "price": 32.56, "stock": 3.2},
  {"id": "bev-048", "cat": "Spirits - Gin", "sup": "Matthew Clark", "code": "00038189", "name": "Edinburgh R & G Gin 40%", "pack": "70cl x6", "unit": "Each", "perCase": 6, "price": 21.92, "stock": 1.4},
  {"id": "bev-049", "cat": "Spirits - Gin", "sup": "Matthew Clark", "code": "00040240", "name": "Tanqueray No.Ten 47.3%", "pack": "70cl x6", "unit": "Each", "perCase": 6, "price": 28.82, "stock": 0.5},
  {"id": "bev-050", "cat": "Spirits - Gin", "sup": "Matthew Clark", "code": "00046586", "name": "Gordons Pink 35%", "pack": "70cl x6", "unit": "Each", "perCase": 6, "price": 14.73, "stock": 3.2},
  {"id": "bev-051", "cat": "Spirits - Gin", "sup": "Heineken", "code": "HK-BOMBAY-CITRON", "name": "Bombay Citron Presse 37.5%", "pack": "70cl", "unit": "Each", "perCase": 1, "price": 22.45, "stock": 1.2},
  {"id": "bev-052", "cat": "Spirits - Gin", "sup": "Heineken", "code": "HK-GORDGIN", "name": "Gordons Gin 37.5%", "pack": "70cl", "unit": "Each", "perCase": 1, "price": 15.88, "stock": 1.2},
  {"id": "bev-053", "cat": "Spirits - Gin", "sup": "Heineken", "code": "HK-GORDMOR", "name": "Gordons Morello Cherry 37.5%", "pack": "70cl", "unit": "Each", "perCase": 1, "price": 17.87, "stock": 1.1},
  {"id": "bev-054", "cat": "Spirits - Gin", "sup": "Heineken", "code": "HK-HENDRICKS", "name": "Hendricks Gin 41.4%", "pack": "70cl", "unit": "Each", "perCase": 1, "price": 26.73, "stock": 0.3},
  {"id": "bev-055", "cat": "Spirits - Gin", "sup": "", "code": "", "name": "Pimms", "pack": "", "unit": "Each", "perCase": 1, "price": 16.42, "stock": 4.5},
  {"id": "bev-056", "cat": "Spirits - Gin", "sup": "", "code": "", "name": "Hendricks Orange", "pack": "", "unit": "Each", "perCase": 1, "price": 27.0, "stock": 1.9},
  {"id": "bev-057", "cat": "Spirits - Gin", "sup": "Heineken", "code": "HK-TANQ-AF", "name": "Tanqueray Alcohol Free 0%", "pack": "70cl", "unit": "Each", "perCase": 1, "price": 13.52, "stock": 0.8},
  {"id": "bev-058", "cat": "Spirits - Rum", "sup": "Matthew Clark", "code": "00015799", "name": "Captain Morgan Spiced", "pack": "1.5L x6", "unit": "Each", "perCase": 6, "price": 31.04, "stock": 1.3},
  {"id": "bev-059", "cat": "Spirits - Rum", "sup": "", "code": "", "name": "Captain Morgan Dark Rum", "pack": "", "unit": "Each", "perCase": 1, "price": 15.96, "stock": 1.3},
  {"id": "bev-060", "cat": "Spirits - Rum", "sup": "", "code": "", "name": "Captain Morgan Dark Spiced Rum", "pack": "", "unit": "Each", "perCase": 1, "price": 19.91, "stock": 1.6},
  {"id": "bev-061", "cat": "Spirits - Rum", "sup": "Matthew Clark", "code": "00026502", "name": "Kraken Black Spiced Rum", "pack": "70cl x6", "unit": "Each", "perCase": 6, "price": 25.04, "stock": 3.5},
  {"id": "bev-062", "cat": "Spirits - Rum", "sup": "Heineken", "code": "HK-BACARDI", "name": "Bacardi Rum 37.5%", "pack": "70cl", "unit": "Each", "perCase": 1, "price": 17.28, "stock": 1.8},
  {"id": "bev-063", "cat": "Spirits - Tequila", "sup": "Matthew Clark", "code": "00047387", "name": "Jose Cuervo Esp Gold 35%", "pack": "70cl x6", "unit": "Each", "perCase": 6, "price": 18.15, "stock": 2.7},
  {"id": "bev-064", "cat": "Spirits - Tequila", "sup": "Heineken", "code": "HK-JC-SILVER", "name": "Jose Cuervo Silver Tequila 35%", "pack": "70cl", "unit": "Each", "perCase": 1, "price": 19.8, "stock": 1.7},
  {"id": "bev-065", "cat": "Other", "sup": "", "code": "", "name": "Licor 43", "pack": "", "unit": "Each", "perCase": 1, "price": 21.24, "stock": 1.0},
  {"id": "bev-066", "cat": "Spirits - Vodka", "sup": "Heineken", "code": "HK-ABS-BLUE", "name": "Absolut Blue 40%", "pack": "70cl", "unit": "Each", "perCase": 1, "price": 16.18, "stock": 2.6},
  {"id": "bev-067", "cat": "Spirits - Vodka", "sup": "Heineken", "code": "HK-ABS-RASP", "name": "Absolut Raspberri 38%", "pack": "70cl", "unit": "Each", "perCase": 1, "price": 17.77, "stock": 0.0},
  {"id": "bev-068", "cat": "Spirits - Vodka", "sup": "Heineken", "code": "HK-ABS-VAN", "name": "Absolut Vanilia 38%", "pack": "70cl", "unit": "Each", "perCase": 1, "price": 17.82, "stock": 3.0},
  {"id": "bev-069", "cat": "Spirits - Vodka", "sup": "Heineken", "code": "HK-GREYGOOSE", "name": "Grey Goose Vodka 40%", "pack": "70cl", "unit": "Each", "perCase": 1, "price": 35.24, "stock": 2.4},
  {"id": "bev-070", "cat": "Spirits - Vodka", "sup": "Heineken", "code": "HK-SMIRNOFF", "name": "Smirnoff Red 37.5%", "pack": "70cl", "unit": "Each", "perCase": 1, "price": 13.61, "stock": 4.0},
  {"id": "bev-071", "cat": "Spirits - Whiskey", "sup": "Brakes", "code": "130920", "name": "Jameson Irish Whiskey", "pack": "70cl", "unit": "Each", "perCase": 1, "price": 24.11, "stock": 2.1},
  {"id": "bev-072", "cat": "Spirits - Whiskey", "sup": "Heineken", "code": "HK-BULLEIT", "name": "Bulleit Bourbon 45%", "pack": "70cl", "unit": "Each", "perCase": 1, "price": 25.85, "stock": 2.2},
  {"id": "bev-073", "cat": "Spirits - Whiskey", "sup": "Heineken", "code": "HK-JD-TENN", "name": "Jack Daniels Tennessee 40%", "pack": "70cl", "unit": "Each", "perCase": 1, "price": 20.79, "stock": 2.9},
  {"id": "bev-074", "cat": "Spirits - Whisky", "sup": "Matthew Clark", "code": "00010520", "name": "Laphroaig 10yo", "pack": "70cl x6", "unit": "Each", "perCase": 6, "price": 36.16, "stock": 2.2},
  {"id": "bev-075", "cat": "Spirits - Whisky", "sup": "Matthew Clark", "code": "00018213", "name": "Monkey Shoulder Malt", "pack": "70cl x6", "unit": "Each", "perCase": 6, "price": 21.94, "stock": 0.0},
  {"id": "bev-076", "cat": "Spirits - Whisky", "sup": "Matthew Clark", "code": "00046437", "name": "Glenmorangie Orig 12yo", "pack": "70cl x6", "unit": "Each", "perCase": 6, "price": 28.33, "stock": 1.7},
  {"id": "bev-077", "cat": "Spirits - Whisky", "sup": "Matthew Clark", "code": "00047689", "name": "Famous Grouse Whisky", "pack": "70cl x6", "unit": "Each", "perCase": 6, "price": 14.2, "stock": 0.9},
  {"id": "bev-078", "cat": "Spirits - Whisky", "sup": "Heineken", "code": "HK-CHIVAS", "name": "Chivas Regal 12yo 40%", "pack": "70cl", "unit": "Each", "perCase": 1, "price": 29.39, "stock": 2.3},
  {"id": "bev-079", "cat": "Spirits - Whisky", "sup": "Heineken", "code": "HK-GLENFIDDICH", "name": "Glenfiddich Special 40%", "pack": "70cl", "unit": "Each", "perCase": 1, "price": 32.17, "stock": 4.4},
  {"id": "bev-080", "cat": "Spirits - Whisky", "sup": "Heineken", "code": "HK-TALISKER", "name": "Talisker 10yo 45.8%", "pack": "70cl", "unit": "Each", "perCase": 1, "price": 37.0, "stock": 0.8},
  {"id": "bev-081", "cat": "Wine - Red", "sup": "Matthew Clark", "code": "00029058", "name": "Nederburg HH Motorcycle", "pack": "75cl x6", "unit": "Each", "perCase": 6, "price": 12.68, "stock": 9.0},
  {"id": "bev-082", "cat": "Wine - Red", "sup": "Matthew Clark", "code": "00044810", "name": "Corte Vigna Merlot", "pack": "75cl x12", "unit": "Each", "perCase": 12, "price": 4.95, "stock": 63.0},
  {"id": "bev-083", "cat": "Wine - Red", "sup": "Matthew Clark", "code": "00047057", "name": "Nyala Cabernet Sauvignon 12.5%", "pack": "75cl x6", "unit": "Each", "perCase": 6, "price": 5.09, "stock": 13.0},
  {"id": "bev-084", "cat": "Wine - Rose", "sup": "Matthew Clark", "code": "00047138", "name": "Mirabello Forever Summer 12.5%", "pack": "75cl x6", "unit": "Each", "perCase": 6, "price": 10.4, "stock": 48.9},
  {"id": "bev-085", "cat": "Wine - Rose", "sup": "Matthew Clark", "code": "00048286", "name": "Wicked Lady White Zinfandel", "pack": "75cl x6", "unit": "Each", "perCase": 6, "price": 4.72, "stock": 14.9},
  {"id": "bev-086", "cat": "Wine - White", "sup": "Matthew Clark", "code": "00043818", "name": "Icauna Petit Chablis", "pack": "75cl x6", "unit": "Each", "perCase": 6, "price": 12.0, "stock": 2.0},
  {"id": "bev-087", "cat": "Wine - White", "sup": "Matthew Clark", "code": "00045856", "name": "Nyala Sauvignon Blanc 11%", "pack": "75cl x6", "unit": "Each", "perCase": 6, "price": 4.81, "stock": 29.3},
  {"id": "bev-088", "cat": "Wine - White", "sup": "Matthew Clark", "code": "00046063", "name": "Vita Lucido Pinot Grigio 10.5%", "pack": "75cl x12", "unit": "Each", "perCase": 12, "price": 5.11, "stock": 42.9},
  {"id": "bev-089", "cat": "Wine - White", "sup": "Matthew Clark", "code": "00049002", "name": "Icauna Chablis", "pack": "75cl x6", "unit": "Each", "perCase": 6, "price": 13.95, "stock": 0.0},
  {"id": "bev-090", "cat": "Other", "sup": "", "code": "", "name": "Campari", "pack": "", "unit": "Each", "perCase": 1, "price": 16.75, "stock": 1.0},
  {"id": "bev-091", "cat": "Other", "sup": "", "code": "", "name": "JD Tennessey Honey", "pack": "", "unit": "Each", "perCase": 1, "price": 24.35, "stock": 4.6},
  {"id": "bev-092", "cat": "Other", "sup": "", "code": "", "name": "Fireball", "pack": "", "unit": "Each", "perCase": 1, "price": 22.3, "stock": 0.8},
  {"id": "bev-093", "cat": "Other", "sup": "", "code": "", "name": "Guinness 0%", "pack": "24", "unit": "Each", "perCase": 1, "price": 45.3, "stock": 1.92},
  {"id": "bev-094", "cat": "Other", "sup": "", "code": "", "name": "Jager", "pack": "", "unit": "Each", "perCase": 1, "price": 21.66, "stock": 0.7},
  {"id": "bev-095", "cat": "Other", "sup": "", "code": "", "name": "Buen Amigo Gold", "pack": "", "unit": "Each", "perCase": 1, "price": 15.89, "stock": 0.9},
  {"id": "bev-096", "cat": "Other", "sup": "", "code": "", "name": "Buen Amigo silver", "pack": "", "unit": "Each", "perCase": 1, "price": 15.89, "stock": 1.8},
  {"id": "bev-097", "cat": "Other", "sup": "", "code": "", "name": "Casamigos", "pack": "", "unit": "Each", "perCase": 1, "price": 35.39, "stock": 0.8},
  {"id": "bev-098", "cat": "Other", "sup": "", "code": "", "name": "Hennessy", "pack": "", "unit": "Each", "perCase": 1, "price": 32.08, "stock": 2.0},
  {"id": "bev-099", "cat": "Other", "sup": "", "code": "", "name": "Dow's Port", "pack": "6", "unit": "Each", "perCase": 1, "price": 67.5, "stock": 1.0},
  {"id": "bev-100", "cat": "Other", "sup": "", "code": "", "name": "Peroni 0%", "pack": "24", "unit": "Each", "perCase": 1, "price": 21.38, "stock": 0.38},
  {"id": "bev-101", "cat": "Other", "sup": "", "code": "", "name": "Remy Martin", "pack": "", "unit": "Each", "perCase": 1, "price": 33.42, "stock": 2.6},
  {"id": "bev-102", "cat": "Other", "sup": "", "code": "", "name": "Schwepps Lime Cordial", "pack": "12", "unit": "Each", "perCase": 1, "price": 22.22, "stock": 0.5},
  {"id": "bev-103", "cat": "Other", "sup": "", "code": "", "name": "Club De Campo Malbec", "pack": "", "unit": "Each", "perCase": 1, "price": 7.65, "stock": 7.6},
  {"id": "bev-104", "cat": "Other", "sup": "", "code": "", "name": "St Hallett Shiraz", "pack": "", "unit": "Each", "perCase": 1, "price": 12.43, "stock": 26.9},
  {"id": "bev-105", "cat": "Other", "sup": "", "code": "", "name": "Rioja", "pack": "6", "unit": "Each", "perCase": 1, "price": 36.42, "stock": 1.9},
  {"id": "bev-106", "cat": "Other", "sup": "", "code": "", "name": "Bello Pino", "pack": "", "unit": "Each", "perCase": 1, "price": 6.09, "stock": 2.0},
  {"id": "bev-107", "cat": "Other", "sup": "", "code": "", "name": "Bello Rose", "pack": "", "unit": "Each", "perCase": 1, "price": 6.09, "stock": 11.2},
  {"id": "bev-108", "cat": "Other", "sup": "", "code": "", "name": "Haystack Chardonnay", "pack": "", "unit": "Each", "perCase": 1, "price": 8.16, "stock": 4.2},
  {"id": "bev-109", "cat": "Other", "sup": "", "code": "", "name": "Villa Blanche Chardonnay", "pack": "", "unit": "Each", "perCase": 1, "price": 8.89, "stock": 4.6},
  {"id": "bev-110", "cat": "Other", "sup": "", "code": "", "name": "Turtle Bay Sauv", "pack": "", "unit": "Each", "perCase": 1, "price": 8.29, "stock": 12.0},
  {"id": "bev-111", "cat": "Other", "sup": "", "code": "", "name": "Serrenello", "pack": "", "unit": "Each", "perCase": 1, "price": 5.49, "stock": 4.0},
  {"id": "bev-112", "cat": "Other", "sup": "", "code": "", "name": "Vina Cerreda Tempranillo", "pack": "", "unit": "Each", "perCase": 1, "price": 9.14, "stock": 25.0},
  {"id": "bev-113", "cat": "Other", "sup": "", "code": "", "name": "Martini Rosso", "pack": "", "unit": "Each", "perCase": 1, "price": 10.49, "stock": 2.0},
  {"id": "bev-114", "cat": "Other", "sup": "", "code": "", "name": "Prosecco Acquerello", "pack": "", "unit": "12", "perCase": 1, "price": 6.29, "stock": 30.0},
  {"id": "bev-115", "cat": "Other", "sup": "", "code": "", "name": "Coco Real Squeeze coconut", "pack": "", "unit": "Each", "perCase": 1, "price": 6.49, "stock": 2.0},
  {"id": "bev-116", "cat": "Other", "sup": "", "code": "", "name": "Moni Watermelon", "pack": "", "unit": "Each", "perCase": 1, "price": 5.49, "stock": 2.0},
  {"id": "bev-117", "cat": "Other", "sup": "", "code": "", "name": "Monin Grenadine", "pack": "", "unit": "Each", "perCase": 1, "price": 5.49, "stock": 2.0}
];
const BEV_PIN = "0356";
